Homework1
made-ml-in-prod-2021/MaksM89 pull request #2
Opened 2021-05-01 00:02 UTC by MaksM89

Взял за основу базовое решение. Изменений не много, зато разобрался в коде.
Датасет кагловский нашел на гитхабе, качается автоматически, если задан параметр в конфиге.
Добавил предикт, который  принимает имя модели и json (pd.DataFrame.to_json()). Сохраняется модель и трансформер, поэтому колонки должны быть такие же, как и на тренировке (больше - не страшно).
Не понял, как в командной строке нужно экранировать символы и какие, в readme.md описаны варианты, которые у меня прошли.

2021-05-04 13:41 UTC, Mikhail-M requested changes
1) структура проекта, нужно все это положить в папку ml_project, так как будут еще задания

2021-05-04 13:41 UTC, Mikhail-M commented on tests/test_predict.py
> +def test_flask_app(client, model_path, data):
Давайте в этом дз без фласка

2021-05-04 13:41 UTC, Mikhail-M commented on ml_project/models/model_fit_predict.py
> +SklearnModel = Union[LogisticRegression]
Union от одного?

2021-05-04 13:41 UTC, Mikhail-M commented on ml_project/features/build_features.py
> +class MyScaleTransformer(TransformerMixin, BaseEstimator):
А зачем нам плохая имплементация того, что уже есть, давайте какой-нибудь кастомчик придумаем, для работы именно с этим датасетом

2021-05-04 13:41 UTC, Mikhail-M commented on tests/models/test_train_model.py
> +def features_and_target(dataset_info) -> Tuple[np.ndarray, np.ndarray]:
вот сюда бы лучше сгенерить данных, чтобы не этот тест не зависил от модуля с фичами

2021-05-09 21:11 UTC, MaksM89 commented on tests/test_predict.py
> +def test_flask_app(client, model_path, data):
Закомментировал

2021-05-09 21:12 UTC, MaksM89 commented on ml_project/models/model_fit_predict.py
> +SklearnModel = Union[LogisticRegression]
Планировал добавить какие-нить модельки в будущем. Исправил

2021-05-09 21:12 UTC, MaksM89 commented on ml_project/features/build_features.py
> +class MyScaleTransformer(TransformerMixin, BaseEstimator):
Сделал новый трансформер, поправил тесты

2021-05-09 21:12 UTC, MaksM89 commented on ml_project/features/build_features.py
> +class MyScaleTransformer(TransformerMixin, BaseEstimator):
Сделал новый трансформер, поправил тесты

2021-05-09 21:12 UTC, MaksM89 commented on tests/models/test_train_model.py
> +def features_and_target(dataset_info) -> Tuple[np.ndarray, np.ndarray]:
Поправил

2021-05-11 13:52 UTC, Mikhail-M requested changes
Прошу исправит в соотвествии с cookiecutter. 
конфиги, данные и артефакты обучения не должны быть смешаны с кодом, должны быть смешны с кодом. Так же тесты должны находиться вне пакета.
ноутбуки тоже.

2021-05-11 19:08 UTC, MaksM89 commented
> Прошу исправить в соотвествии с cookiecutter.
> конфиги, данные и артефакты обучения не должны быть смешаны с кодом, должны быть смешны с кодом. Так же тесты должны находиться вне пакета.
> ноутбуки тоже.

Не понял. В прошлый раз было 

> структура проекта, нужно все это положить в папку ml_project, так как будут еще задания
у меня в директории были папки data, models, notebooks, я их переместил в ml_project. Какая должна быть в итоге структура?

2021-05-14 20:34 UTC, MaksM89 commented
Вернулся к прошлой структуре

2021-05-21 15:10 UTC, Mikhail-M approved these changes
Баллы: 32

2021-05-21 15:17 UTC, merged